In [17]:
import pandas as pd

In [18]:
df = pd.read_csv('data.csv')

In [19]:
df.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       NaN     409.1
1        60    117     145.0     479.0
2        60    103     135.0     340.0
3        45    109     175.0     282.4
4        45    117     148.0     406.0

In [20]:
tempdict = {'col1':[1,2,3],'col2':[4,5,6],'col3':[7,8,9]}

In [21]:
dictdf = pd.DataFrame.from_dict(tempdict)

In [22]:
df.head(10)

   Duration  Pulse  Maxpulse  Calories
0        60    110       NaN     409.1
1        60    117     145.0     479.0
2        60    103     135.0     340.0
3        45    109     175.0     282.4
4        45    117     148.0     406.0
5        60    102     127.0     300.0
6        60    110     136.0     374.0
7        45    104     134.0     253.3
8        30    109     133.0     195.1
9        60     98     124.0     269.0

In [23]:
dictdf.head()

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9

In [24]:
df.tail()

     Duration  Pulse  Maxpulse  Calories
164        60    105     140.0     290.8
165        60    110     145.0     300.0
166        60    115     145.0     310.2
167        75    120     150.0     320.4
168        75    125     150.0     330.4

In [25]:
df.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [26]:
df.dtypes

Duration      int64
Pulse         int64
Maxpulse    float64
Calories    float64
dtype: object

In [27]:
dictdf.describe()

       col1  col2  col3
count   3.0   3.0   3.0
mean    2.0   5.0   8.0
std     1.0   1.0   1.0
min     1.0   4.0   7.0
25%     1.5   4.5   7.5
50%     2.0   5.0   8.0
75%     2.5   5.5   8.5
max     3.0   6.0   9.0

In [33]:
df['Pulse']

0      110
1      117
2      103
3      109
4      117
      ...
164    105
165    110
166    115
167    120
168    125
Name: Pulse, Length: 169, dtype: int64

In [34]:
df.Pulse.unique()

array([110, 117, 103, 109, 102, 104,  98, 100, 106,  90,  97, 108, 130,
       105,  92, 101,  93, 107, 114, 111,  99, 123, 118, 136, 121, 115,
       153, 159, 149, 151, 129,  83,  80, 150,  95, 152, 137, 124, 116,
       112, 119, 113, 141, 122,  85, 120, 125], dtype=int64)

In [37]:
df.iloc[1]

Duration     60.0
Pulse       117.0
Maxpulse    145.0
Calories    479.0
Name: 1, dtype: float64

In [38]:
data = df.copy()
data.set_index('Pulse',inplace=True)

In [39]:
data.head()

       Duration  Maxpulse  Calories
Pulse
110          60       NaN     409.1
117          60     145.0     479.0
103          60     135.0     340.0
109          45     175.0     282.4
117          45     148.0     406.0

In [47]:
data.iloc[0:]

       Duration  Maxpulse  Calories
Pulse
110          60       NaN     409.1
117          60     145.0     479.0
103          60     135.0     340.0
109          45     175.0     282.4
117          45     148.0     406.0
...         ...       ...       ...
105          60     140.0     290.8
110          60     145.0     300.0
115          60     145.0     310.2
120          75     150.0     320.4
125          75     150.0     330.4

[169 rows x 3 columns]

In [48]:
df.isnull().sum()

Duration    0
Pulse       0
Maxpulse    1
Calories    5
dtype: int64

In [50]:
df.drop('Duration',axis=1)

     Pulse  Maxpulse  Calories
0      110       NaN     409.1
1      117     145.0     479.0
2      103     135.0     340.0
3      109     175.0     282.4
4      117     148.0     406.0
..     ...       ...       ...
164    105     140.0     290.8
165    110     145.0     300.0
166    115     145.0     310.2
167    120     150.0     320.4
168    125     150.0     330.4

[169 rows x 3 columns]